<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbfcd877a920142fe5bb9c05869e6f022
{
    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'Vendor\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Vendor\\' => 
        array (
            0 => __DIR__ . '/..' . '/steezer/steeze-vendor/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbfcd877a920142fe5bb9c05869e6f022::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbfcd877a920142fe5bb9c05869e6f022::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
